export const MUMBAI_AREAS = [
  "Altamount Road",
  "Andheri East",
  "Andheri West",
  "Bandra East",
  "Bandra West",
  "Bhandup",
  "Bhayandar",
  "Borivali East",
  "Borivali West",
  "Breach Candy",
  "Byculla",
  "Chembur",
  "Churchgate",
  "Colaba",
  "Cuffe Parade",
  "Dadar East",
  "Dadar West",
  "Dahisar",
  "Dharavi",
  "Fort",
  "Ghatkopar East",
  "Ghatkopar West",
  "Girgaon",
  "Goregaon East",
  "Goregaon West",
  "Grant Road",
  "Jogeshwari",
  "Juhu",
  "Kalyan",
  "Kandivali East",
  "Kandivali West",
  "Kanjurmarg",
  "Khar West",
  "Kurla",
  "Lower Parel",
  "Mahalaxmi",
  "Mahim",
  "Malabar Hill",
  "Malad East",
  "Malad West",
  "Marine Drive",
  "Matunga",
  "Mira Road",
  "Mulund East",
  "Mulund West",
  "Nariman Point",
  "Navi Mumbai - Airoli",
  "Navi Mumbai - Belapur",
  "Navi Mumbai - Ghansoli",
  "Navi Mumbai - Kharghar",
  "Navi Mumbai - Kopar Khairane",
  "Navi Mumbai - Nerul",
  "Navi Mumbai - Panvel",
  "Navi Mumbai - Sanpada",
  "Navi Mumbai - Seawoods",
  "Navi Mumbai - Vashi",
  "Oshiwara",
  "Parel",
  "Powai",
  "Prabhadevi",
  "Sakinaka",
  "Santacruz East",
  "Santacruz West",
  "Sion",
  "Tardeo",
  "Thane - Ghodbunder Road",
  "Thane - Majiwada",
  "Thane - Vasant Vihar",
  "Thane East",
  "Thane West",
  "Vasai",
  "Vidyavihar",
  "Vikhroli",
  "Vile Parle East",
  "Vile Parle West",
  "Virar",
  "Wadala",
  "Worli"
];
